import React from "react";
import { Product } from "@/types/product.types";

const AISummaryContent = ({ product }: { product: Product }) => {
  return (
    <section>
      <h3 className="text-xl sm:text-2xl font-bold text-black mb-5 sm:mb-6">
        AI-Powered Summary
      </h3>
      {product.aiSummary ? (
        <div className="prose prose-sm max-w-none">
          <p className="text-sm sm:text-base text-black/80 leading-7">
            {product.aiSummary}
          </p>
        </div>
      ) : (
        <div className="bg-[#F0F0F0] rounded-2xl p-8 text-center">
          <div className="text-4xl mb-4">🤖</div>
          <p className="text-black/60 text-sm sm:text-base mb-2">
            AI summary not yet available for this product.
          </p>
          <p className="text-black/40 text-xs sm:text-sm">
            An AI-generated summary highlighting key features and use cases will
            appear here once generated by an admin.
          </p>
        </div>
      )}
    </section>
  );
};

export default AISummaryContent;
