/**
 * THIS FILE WAS GENERATED BY CLAUDE
 * 
 * Seed script: Wipes Firestore, then populates 25 products, 11 users, and 50 orders.
 *
 * Usage:
 *   npx tsx scripts/seed-products.ts
 *
 * Prerequisites:
 *   1. Fill in your Firebase config in .env.local
 *   2. npm install tsx (dev dependency) — or use npx
 */

import { initializeApp } from "firebase/app";
import {
  getFirestore,
  collection,
  addDoc,
  doc,
  setDoc,
  getDocs,
  deleteDoc,
  Timestamp,
} from "firebase/firestore";
import {
  getAuth,
  createUserWithEmailAndPassword,
  signInWithEmailAndPassword,
} from "firebase/auth";
import * as dotenv from "dotenv";
import path from "path";

// Load .env.local
dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);
const auth = getAuth(app);

// ─── Types ───────────────────────────────────────────────────────────────────

type PaymentType = "EFT" | "Card" | "Cash on Delivery";

type Address = {
  street: string;
  suburb: string;
  city: string;
  province: string;
  postalCode: string;
};

type SeedProductBase = {
  name: string;
  brand: string;
  price: number;
  cost: number;
  category: string;
  specs: {
    processor: string;
    ram: string;
    storage: string;
    gpu: string;
    screenSize: string;
    display: string;
    os: string;
    weight: string;
  };
  images: string[];
  tags: string[];
  description: string;
  discount: { amount: number; percentage: number };
  rating: number;
  featured?: boolean;
};

type DemoUser = {
  displayName: string;
  email: string;
  role: "customer" | "admin";
  createdAt: Date;
};

type OrderPlan = {
  userIdx: number;
  date: Date;
  items: { productIdx: number; qty: number }[];
  paymentType: PaymentType;
};

// ─── Helper functions ────────────────────────────────────────────────────────

/** Wipe all documents in a Firestore collection */
async function wipeCollection(name: string): Promise<number> {
  const snapshot = await getDocs(collection(db, name));
  let count = 0;
  for (const d of snapshot.docs) {
    await deleteDoc(doc(db, name, d.id));
    count++;
  }
  return count;
}

/** Small delay to avoid Firebase Auth rate limiting */
const delay = (ms: number) => new Promise((r) => setTimeout(r, ms));

/** Generate a random 8-character alphanumeric mixed-case friend code (same as src/lib/utils.ts) */
function generateFriendCode(): string {
  const chars =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  let code = "";
  for (let i = 0; i < 8; i++) {
    code += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return code;
}

// ─── Sample shipping addresses (South African) ──────────────────────────────

const ADDRESSES: Address[] = [
  {
    street: "12 Main Road",
    suburb: "Gardens",
    city: "Cape Town",
    province: "Western Cape",
    postalCode: "8001",
  },
  {
    street: "45 Rivonia Boulevard",
    suburb: "Sandton",
    city: "Johannesburg",
    province: "Gauteng",
    postalCode: "2196",
  },
  {
    street: "88 Beach Road",
    suburb: "Umhlanga",
    city: "Durban",
    province: "KwaZulu-Natal",
    postalCode: "4320",
  },
  {
    street: "23 Church Street",
    suburb: "Arcadia",
    city: "Pretoria",
    province: "Gauteng",
    postalCode: "0083",
  },
  {
    street: "7 Long Street",
    suburb: "CBD",
    city: "Cape Town",
    province: "Western Cape",
    postalCode: "8000",
  },
];

// ─── Demo users (10 customers + 1 admin) ─────────────────────────────────────
// createdAt dates are set a few days before each user's first order so the
// "New Customers per Month" chart in the Customer tab looks natural.

const DEMO_PASSWORD = "Password123!";

const DEMO_USERS: DemoUser[] = [
  {
    displayName: "Alice Smith",
    email: "alice@email.com",
    role: "customer",
    createdAt: new Date(2025, 3, 28),
  },
  {
    displayName: "Bob Johnson",
    email: "bob@email.com",
    role: "customer",
    createdAt: new Date(2025, 3, 30),
  },
  {
    displayName: "Charlie Brown",
    email: "charlie@email.com",
    role: "customer",
    createdAt: new Date(2025, 4, 28),
  },
  {
    displayName: "Diana Lee",
    email: "diana@email.com",
    role: "customer",
    createdAt: new Date(2025, 5, 28),
  },
  {
    displayName: "Ethan Davis",
    email: "ethan@email.com",
    role: "customer",
    createdAt: new Date(2025, 6, 28),
  },
  {
    displayName: "Fiona Clark",
    email: "fiona@email.com",
    role: "customer",
    createdAt: new Date(2025, 7, 28),
  },
  {
    displayName: "George Miller",
    email: "george@email.com",
    role: "customer",
    createdAt: new Date(2025, 8, 26),
  },
  {
    displayName: "Hannah Wilson",
    email: "hannah@email.com",
    role: "customer",
    createdAt: new Date(2025, 9, 26),
  },
  {
    displayName: "Ivan Moore",
    email: "ivan@email.com",
    role: "customer",
    createdAt: new Date(2025, 10, 24),
  },
  {
    displayName: "Julia Taylor",
    email: "julia@email.com",
    role: "customer",
    createdAt: new Date(2025, 11, 28),
  },
  {
    displayName: "Admin",
    email: "admin@email.com",
    role: "admin",
    createdAt: new Date(2025, 3, 1),
  },
];

// ─── Products (25 laptops — UNCHANGED from original seed) ────────────────────

const products: SeedProductBase[] = [
  // ===== GAMING (5) =====
  {
    name: "ASUS ROG Strix G16",
    brand: "ASUS",
    price: 32999,
    cost: 22000,
    category: "gaming",
    specs: {
      processor: "Intel Core i7-13650HX",
      ram: "16GB DDR5",
      storage: "1TB NVMe SSD",
      gpu: "NVIDIA RTX 4060 8GB",
      screenSize: '16"',
      display: "1920x1200 IPS 165Hz",
      os: "Windows 11 Home",
      weight: "2.5 kg",
    },
    images: ["/images/laptops/asus-rog-strix-g16.webp"],
    tags: ["gaming", "rgb", "high-refresh", "nvidia"],
    description:
      "A powerful gaming laptop featuring an Intel i7 processor and RTX 4060 GPU, designed for smooth gameplay at high settings.",
    discount: { amount: 0, percentage: 10 },
    rating: 4.6,
    featured: true,
  },
  {
    name: "Lenovo Legion 5 Pro",
    brand: "Lenovo",
    price: 28499,
    cost: 19000,
    category: "gaming",
    specs: {
      processor: "AMD Ryzen 7 7745HX",
      ram: "16GB DDR5",
      storage: "512GB NVMe SSD",
      gpu: "NVIDIA RTX 4060 8GB",
      screenSize: '16"',
      display: "2560x1600 IPS 165Hz",
      os: "Windows 11 Home",
      weight: "2.5 kg",
    },
    images: ["/images/laptops/lenovo-legion-5-pro.webp"],
    tags: ["gaming", "QHD", "ryzen", "nvidia"],
    description:
      "A high-performance gaming laptop with a stunning QHD display and powerful AMD Ryzen processor for competitive and AAA gaming.",
    discount: { amount: 0, percentage: 0 },
    rating: 4.5,
  },
  {
    name: "MSI Katana 15",
    brand: "MSI",
    price: 19999,
    cost: 13500,
    category: "gaming",
    specs: {
      processor: "Intel Core i5-12450H",
      ram: "8GB DDR5",
      storage: "512GB NVMe SSD",
      gpu: "NVIDIA RTX 4050 6GB",
      screenSize: '15.6"',
      display: "1920x1080 IPS 144Hz",
      os: "Windows 11 Home",
      weight: "2.25 kg",
    },
    images: ["/images/laptops/msi-katana-15.webp"],
    tags: ["gaming", "budget", "nvidia", "entry-level"],
    description:
      "An affordable entry into gaming with RTX 4050 graphics and a 144Hz display, ideal for esports and lighter titles.",
    discount: { amount: 0, percentage: 15 },
    rating: 4.0,
  },
  {
    name: "HP Omen 16",
    brand: "HP",
    price: 35999,
    cost: 24500,
    category: "gaming",
    specs: {
      processor: "Intel Core i7-13700HX",
      ram: "32GB DDR5",
      storage: "1TB NVMe SSD",
      gpu: "NVIDIA RTX 4070 8GB",
      screenSize: '16.1"',
      display: "2560x1440 IPS 165Hz",
      os: "Windows 11 Home",
      weight: "2.37 kg",
    },
    images: ["/images/laptops/hp-omen-16.webp"],
    tags: ["gaming", "premium", "QHD", "nvidia"],
    description:
      "Premium gaming experience with RTX 4070 and QHD 165Hz display. Built for serious gamers who want no compromise.",
    discount: { amount: 0, percentage: 0 },
    rating: 4.7,
  },
  {
    name: "Acer Nitro V 15",
    brand: "Acer",
    price: 16499,
    cost: 11000,
    category: "gaming",
    specs: {
      processor: "AMD Ryzen 5 7535HS",
      ram: "8GB DDR5",
      storage: "512GB NVMe SSD",
      gpu: "NVIDIA RTX 4050 6GB",
      screenSize: '15.6"',
      display: "1920x1080 IPS 144Hz",
      os: "Windows 11 Home",
      weight: "2.1 kg",
    },
    images: ["/images/laptops/acer-nitro-v-15.webp"],
    tags: ["gaming", "budget", "nvidia", "amd"],
    description:
      "Budget-friendly gaming with RTX 4050 and a fast display. Perfect for students who game on the side.",
    discount: { amount: 1000, percentage: 0 },
    rating: 3.9,
  },

  // ===== BUSINESS (5) =====
  {
    name: "Lenovo ThinkPad X1 Carbon Gen 11",
    brand: "Lenovo",
    price: 34999,
    cost: 24000,
    category: "business",
    specs: {
      processor: "Intel Core i7-1365U",
      ram: "16GB LPDDR5",
      storage: "512GB NVMe SSD",
      gpu: "Intel Iris Xe",
      screenSize: '14"',
      display: "2560x1600 IPS 400 nits",
      os: "Windows 11 Pro",
      weight: "1.12 kg",
    },
    images: ["/images/laptops/lenovo-thinkpad-x1-carbon.webp"],
    tags: ["business", "lightweight", "thinkpad", "professional"],
    description:
      "The gold standard for business laptops. Ultra-light carbon fiber build, legendary ThinkPad keyboard, and all-day battery.",
    discount: { amount: 0, percentage: 0 },
    rating: 4.8,
    featured: true,
  },
  {
    name: "Dell Latitude 7440",
    brand: "Dell",
    price: 27999,
    cost: 18500,
    category: "business",
    specs: {
      processor: "Intel Core i7-1365U",
      ram: "16GB LPDDR5",
      storage: "512GB NVMe SSD",
      gpu: "Intel Iris Xe",
      screenSize: '14"',
      display: "1920x1200 IPS",
      os: "Windows 11 Pro",
      weight: "1.37 kg",
    },
    images: ["/images/laptops/dell-latitude-7440.webp"],
    tags: ["business", "enterprise", "dell", "professional"],
    description:
      "Enterprise-grade business laptop with robust security features, excellent keyboard, and manageable fleet deployment.",
    discount: { amount: 0, percentage: 10 },
    rating: 4.4,
  },
  {
    name: "HP EliteBook 840 G10",
    brand: "HP",
    price: 29499,
    cost: 20000,
    category: "business",
    specs: {
      processor: "Intel Core i7-1365U",
      ram: "16GB DDR5",
      storage: "512GB NVMe SSD",
      gpu: "Intel Iris Xe",
      screenSize: '14"',
      display: "1920x1200 IPS 400 nits",
      os: "Windows 11 Pro",
      weight: "1.36 kg",
    },
    images: ["/images/laptops/hp-elitebook-840.webp"],
    tags: ["business", "enterprise", "hp", "secure"],
    description:
      "A premium business notebook with MIL-STD durability, HP Wolf Security, and a bright outdoor-readable display.",
    discount: { amount: 0, percentage: 0 },
    rating: 4.5,
  },
  {
    name: "Lenovo ThinkPad T14s Gen 4",
    brand: "Lenovo",
    price: 24999,
    cost: 16500,
    category: "business",
    specs: {
      processor: "AMD Ryzen 7 PRO 7840U",
      ram: "16GB LPDDR5",
      storage: "512GB NVMe SSD",
      gpu: "AMD Radeon 780M",
      screenSize: '14"',
      display: "1920x1200 IPS",
      os: "Windows 11 Pro",
      weight: "1.22 kg",
    },
    images: ["/images/laptops/lenovo-thinkpad-t14s.webp"],
    tags: ["business", "amd", "thinkpad", "lightweight"],
    description:
      "Business performance meets AMD efficiency. Great battery life and the trusted ThinkPad build quality at a competitive price.",
    discount: { amount: 2000, percentage: 0 },
    rating: 4.3,
  },
  {
    name: "Dell Vostro 3520",
    brand: "Dell",
    price: 12999,
    cost: 8500,
    category: "business",
    specs: {
      processor: "Intel Core i5-1235U",
      ram: "8GB DDR4",
      storage: "256GB NVMe SSD",
      gpu: "Intel Iris Xe",
      screenSize: '15.6"',
      display: "1920x1080 IPS",
      os: "Windows 11 Pro",
      weight: "1.66 kg",
    },
    images: ["/images/laptops/dell-vostro-3520.webp"],
    tags: ["business", "budget", "dell", "small-business"],
    description:
      "Reliable and affordable business laptop for small businesses and startups. Comes with Windows Pro for domain management.",
    discount: { amount: 0, percentage: 0 },
    rating: 3.8,
  },

  // ===== ULTRABOOK (5) =====
  {
    name: "Apple MacBook Air M3",
    brand: "Apple",
    price: 22999,
    cost: 17000,
    category: "ultrabook",
    specs: {
      processor: "Apple M3 8-core",
      ram: "8GB Unified",
      storage: "256GB SSD",
      gpu: "Apple M3 10-core GPU",
      screenSize: '13.6"',
      display: "2560x1664 Liquid Retina",
      os: "macOS Sonoma",
      weight: "1.24 kg",
    },
    images: ["/images/laptops/macbook-air-m3.webp"],
    tags: ["ultrabook", "apple", "lightweight", "fanless"],
    description:
      "The fanless MacBook Air with M3 chip delivers incredible performance in a thin, light design with an all-day battery.",
    discount: { amount: 0, percentage: 0 },
    rating: 4.9,
    featured: true,
  },
  {
    name: "Dell XPS 13 Plus",
    brand: "Dell",
    price: 29999,
    cost: 20000,
    category: "ultrabook",
    specs: {
      processor: "Intel Core i7-1360P",
      ram: "16GB LPDDR5",
      storage: "512GB NVMe SSD",
      gpu: "Intel Iris Xe",
      screenSize: '13.4"',
      display: "1920x1200 OLED Touch",
      os: "Windows 11 Home",
      weight: "1.23 kg",
    },
    images: ["/images/laptops/dell-xps-13-plus.webp"],
    tags: ["ultrabook", "oled", "premium", "touch"],
    description:
      "A stunning ultrabook with an edge-to-edge OLED touchscreen, invisible trackpad, and premium CNC aluminum build.",
    discount: { amount: 0, percentage: 15 },
    rating: 4.5,
  },
  {
    name: "ASUS ZenBook 14 OLED",
    brand: "ASUS",
    price: 19999,
    cost: 13500,
    category: "ultrabook",
    specs: {
      processor: "AMD Ryzen 7 7840U",
      ram: "16GB LPDDR5",
      storage: "512GB NVMe SSD",
      gpu: "AMD Radeon 780M",
      screenSize: '14"',
      display: "2880x1800 OLED 90Hz",
      os: "Windows 11 Home",
      weight: "1.2 kg",
    },
    images: ["/images/laptops/asus-zenbook-14-oled.webp"],
    tags: ["ultrabook", "oled", "lightweight", "amd"],
    description:
      "A gorgeous 2.8K OLED display in a compact, lightweight body. Exceptional color accuracy for creatives and everyday users alike.",
    discount: { amount: 0, percentage: 0 },
    rating: 4.6,
  },
  {
    name: "Apple MacBook Pro 14 M3 Pro",
    brand: "Apple",
    price: 42999,
    cost: 33000,
    category: "ultrabook",
    specs: {
      processor: "Apple M3 Pro 12-core",
      ram: "18GB Unified",
      storage: "512GB SSD",
      gpu: "Apple M3 Pro 18-core GPU",
      screenSize: '14.2"',
      display: "3024x1964 Liquid Retina XDR",
      os: "macOS Sonoma",
      weight: "1.61 kg",
    },
    images: ["/images/laptops/macbook-pro-14-m3.webp"],
    tags: ["ultrabook", "apple", "professional", "creative"],
    description:
      "Pro-level performance for developers, designers, and video editors. The M3 Pro chip handles demanding creative workloads with ease.",
    discount: { amount: 0, percentage: 0 },
    rating: 4.9,
    featured: true,
  },
  {
    name: "HP Spectre x360 14",
    brand: "HP",
    price: 31999,
    cost: 21500,
    category: "ultrabook",
    specs: {
      processor: "Intel Core i7-1355U",
      ram: "16GB LPDDR5",
      storage: "1TB NVMe SSD",
      gpu: "Intel Iris Xe",
      screenSize: '14"',
      display: "2880x1800 OLED Touch",
      os: "Windows 11 Home",
      weight: "1.39 kg",
    },
    images: ["/images/laptops/hp-spectre-x360-14.webp"],
    tags: ["ultrabook", "2-in-1", "oled", "touch", "convertible"],
    description:
      "A premium 2-in-1 convertible with a stunning OLED touch display, gem-cut design, and versatile tent/tablet modes.",
    discount: { amount: 3000, percentage: 0 },
    rating: 4.4,
  },

  // ===== STUDENT (5) =====
  {
    name: "Acer Aspire 3 15",
    brand: "Acer",
    price: 8999,
    cost: 5800,
    category: "student",
    specs: {
      processor: "AMD Ryzen 5 7520U",
      ram: "8GB DDR5",
      storage: "256GB NVMe SSD",
      gpu: "AMD Radeon 610M",
      screenSize: '15.6"',
      display: "1920x1080 IPS",
      os: "Windows 11 Home",
      weight: "1.78 kg",
    },
    images: ["/images/laptops/acer-aspire-3-15.webp"],
    tags: ["student", "budget", "affordable", "everyday"],
    description:
      "A reliable everyday laptop for students on a budget. Handles web browsing, documents, and light media with ease.",
    discount: { amount: 0, percentage: 0 },
    rating: 3.8,
  },
  {
    name: "Lenovo IdeaPad Slim 3",
    brand: "Lenovo",
    price: 9999,
    cost: 6500,
    category: "student",
    specs: {
      processor: "Intel Core i5-1335U",
      ram: "8GB DDR4",
      storage: "512GB NVMe SSD",
      gpu: "Intel Iris Xe",
      screenSize: '15.6"',
      display: "1920x1080 IPS",
      os: "Windows 11 Home",
      weight: "1.62 kg",
    },
    images: ["/images/laptops/lenovo-ideapad-slim-3.webp"],
    tags: ["student", "budget", "lenovo", "everyday"],
    description:
      "Great value for students with a spacious 512GB SSD, comfortable keyboard, and decent battery life for long lecture days.",
    discount: { amount: 0, percentage: 10 },
    rating: 4.0,
  },
  {
    name: "HP 15s",
    brand: "HP",
    price: 7999,
    cost: 5200,
    category: "student",
    specs: {
      processor: "Intel Core i3-1215U",
      ram: "8GB DDR4",
      storage: "256GB NVMe SSD",
      gpu: "Intel UHD Graphics",
      screenSize: '15.6"',
      display: "1920x1080 SVA",
      os: "Windows 11 Home S",
      weight: "1.69 kg",
    },
    images: ["/images/laptops/hp-15s.webp"],
    tags: ["student", "budget", "hp", "entry-level"],
    description:
      "The most affordable option for basic student needs. Perfect for note-taking, email, and web-based coursework.",
    discount: { amount: 0, percentage: 0 },
    rating: 3.5,
  },
  {
    name: "ASUS VivoBook 15",
    brand: "ASUS",
    price: 10999,
    cost: 7200,
    category: "student",
    featured: true,
    specs: {
      processor: "AMD Ryzen 5 7530U",
      ram: "8GB DDR4",
      storage: "512GB NVMe SSD",
      gpu: "AMD Radeon Graphics",
      screenSize: '15.6"',
      display: "1920x1080 IPS",
      os: "Windows 11 Home",
      weight: "1.7 kg",
    },
    images: ["/images/laptops/asus-vivobook-15.webp"],
    tags: ["student", "everyday", "asus", "colorful"],
    description:
      "Stylish and capable student laptop with an ergonomic hinge, fast SSD, and a lightweight design for campus life.",
    discount: { amount: 0, percentage: 0 },
    rating: 4.1,
  },
  {
    name: "Dell Inspiron 15 3530",
    brand: "Dell",
    price: 11499,
    cost: 7500,
    category: "student",
    specs: {
      processor: "Intel Core i5-1335U",
      ram: "8GB DDR4",
      storage: "512GB NVMe SSD",
      gpu: "Intel Iris Xe",
      screenSize: '15.6"',
      display: "1920x1080 IPS",
      os: "Windows 11 Home",
      weight: "1.65 kg",
    },
    images: ["/images/laptops/dell-inspiron-15.webp"],
    tags: ["student", "dell", "reliable", "mainstream"],
    description:
      "A well-rounded student laptop from Dell with a comfortable keyboard, good display, and solid build quality.",
    discount: { amount: 0, percentage: 5 },
    rating: 4.0,
  },

  // ===== WORKSTATION (5) =====
  {
    name: "Dell Precision 5680",
    brand: "Dell",
    price: 59999,
    cost: 42000,
    category: "workstation",
    featured: true,
    specs: {
      processor: "Intel Core i9-13900H",
      ram: "32GB DDR5",
      storage: "1TB NVMe SSD",
      gpu: "NVIDIA RTX 3500 Ada 12GB",
      screenSize: '16"',
      display: "3840x2400 OLED Touch",
      os: "Windows 11 Pro",
      weight: "1.91 kg",
    },
    images: ["/images/laptops/dell-precision-5680.webp"],
    tags: ["workstation", "professional", "CAD", "4K", "oled"],
    description:
      "A mobile workstation for engineers and 3D professionals. ISV-certified for AutoCAD, SolidWorks, and other pro apps.",
    discount: { amount: 0, percentage: 0 },
    rating: 4.7,
  },
  {
    name: "Lenovo ThinkPad P16s Gen 2",
    brand: "Lenovo",
    price: 38999,
    cost: 26500,
    category: "workstation",
    specs: {
      processor: "Intel Core i7-1360P",
      ram: "32GB DDR5",
      storage: "1TB NVMe SSD",
      gpu: "NVIDIA RTX A500 4GB",
      screenSize: '16"',
      display: "2560x1600 IPS",
      os: "Windows 11 Pro",
      weight: "1.73 kg",
    },
    images: ["/images/laptops/lenovo-thinkpad-p16s.webp"],
    tags: ["workstation", "thinkpad", "ISV-certified", "engineering"],
    description:
      "A lighter mobile workstation with professional NVIDIA graphics, ISV certification, and classic ThinkPad reliability.",
    discount: { amount: 0, percentage: 10 },
    rating: 4.4,
  },
  {
    name: "HP ZBook Fury 16 G10",
    brand: "HP",
    price: 64999,
    cost: 45000,
    category: "workstation",
    specs: {
      processor: "Intel Core i9-13950HX",
      ram: "64GB DDR5",
      storage: "2TB NVMe SSD",
      gpu: "NVIDIA RTX 5000 Ada 16GB",
      screenSize: '16"',
      display: "3840x2400 IPS DreamColor",
      os: "Windows 11 Pro",
      weight: "2.85 kg",
    },
    images: ["/images/laptops/hp-zbook-fury-16.webp"],
    tags: ["workstation", "premium", "64GB", "4K", "creative"],
    description:
      "The ultimate mobile workstation. 64GB RAM, 4K DreamColor display, and top-tier NVIDIA Ada GPU for the most demanding workloads.",
    discount: { amount: 5000, percentage: 0 },
    rating: 4.8,
  },
  {
    name: "Apple MacBook Pro 16 M3 Max",
    brand: "Apple",
    price: 74999,
    cost: 58000,
    category: "workstation",
    featured: true,
    specs: {
      processor: "Apple M3 Max 16-core",
      ram: "48GB Unified",
      storage: "1TB SSD",
      gpu: "Apple M3 Max 40-core GPU",
      screenSize: '16.2"',
      display: "3456x2234 Liquid Retina XDR",
      os: "macOS Sonoma",
      weight: "2.14 kg",
    },
    images: ["/images/laptops/macbook-pro-16-m3-max.webp"],
    tags: ["workstation", "apple", "creative", "video-editing", "premium"],
    description:
      "The most powerful MacBook ever. M3 Max drives 8K video editing, 3D rendering, and massive datasets without breaking a sweat.",
    discount: { amount: 0, percentage: 0 },
    rating: 4.9,
  },
  {
    name: "ASUS ProArt StudioBook 16 OLED",
    brand: "ASUS",
    price: 49999,
    cost: 35000,
    category: "workstation",
    specs: {
      processor: "Intel Core i9-13980HX",
      ram: "32GB DDR5",
      storage: "1TB NVMe SSD",
      gpu: "NVIDIA RTX 4070 8GB",
      screenSize: '16"',
      display: "3840x2400 OLED",
      os: "Windows 11 Pro",
      weight: "2.4 kg",
    },
    images: ["/images/laptops/asus-proart-studiobook-16.webp"],
    tags: ["workstation", "creative", "oled", "4K", "color-accurate"],
    description:
      "Built for creative professionals with a Pantone-validated 4K OLED display and powerful specs for video editing and design.",
    discount: { amount: 0, percentage: 5 },
    rating: 4.6,
  },
];

// ─── View counts per product (diverse conversion rates ~4–12%) ───────────────
//
// Pre-computed to match the sales distribution from the 50 orders below.
// Each product gets views proportional to its sales but with intentionally
// varied conversion rates so the "Views vs Purchases" bar chart looks realistic.
//
// Idx:  0    1    2    3    4    5    6    7    8    9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24
const VIEW_COUNTS = [
  85, 62, 45, 55, 28, 38, 30, 35, 22, 18, 110, 52, 40, 72, 38, 65, 42, 34, 24,
  20, 25, 28, 15, 32, 26,
];

// ─── Order plans (50 orders, May 2025 – Feb 2026) ────────────────────────────
//
// Designed to populate all three report tabs with rich, varied data:
//
// Finance tab:  Orders spread across 10 months for the revenue time-series.
//               Mixed payment types (≈50% Card, 32% EFT, 18% Cash on Delivery).
//               totalCost derived from product cost for profit margin KPIs.
//
// Customer tab: Each user's first order defines their "new customer" month.
//               9/10 customers are repeat buyers (90% repeat rate).
//               Top spender (Alice) has 10 orders for clear ranking.
//
// Products tab: All 25 products are sold at least once.
//               MacBook Air M3 is the top seller (8 units).
//               Sales span all 5 categories for a balanced pie chart.

const ORDER_PLANS: OrderPlan[] = [
  // ── May 2025 (3 orders) — Users 0 & 1 first appear ─────────────────────
  {
    userIdx: 0,
    date: new Date(2025, 4, 5),
    items: [{ productIdx: 10, qty: 1 }],
    paymentType: "Card",
  },
  {
    userIdx: 0,
    date: new Date(2025, 4, 18),
    items: [{ productIdx: 0, qty: 1 }],
    paymentType: "EFT",
  },
  {
    userIdx: 1,
    date: new Date(2025, 4, 22),
    items: [{ productIdx: 13, qty: 1 }],
    paymentType: "Card",
  },

  // ── Jun 2025 (4 orders) — User 2 first appears ─────────────────────────
  {
    userIdx: 2,
    date: new Date(2025, 5, 3),
    items: [
      { productIdx: 15, qty: 1 },
      { productIdx: 4, qty: 1 },
    ],
    paymentType: "EFT",
  },
  {
    userIdx: 0,
    date: new Date(2025, 5, 12),
    items: [{ productIdx: 5, qty: 1 }],
    paymentType: "Card",
  },
  {
    userIdx: 1,
    date: new Date(2025, 5, 20),
    items: [{ productIdx: 10, qty: 1 }],
    paymentType: "Cash on Delivery",
  },
  {
    userIdx: 2,
    date: new Date(2025, 5, 28),
    items: [{ productIdx: 1, qty: 1 }],
    paymentType: "Card",
  },

  // ── Jul 2025 (4 orders) — User 3 first appears ─────────────────────────
  {
    userIdx: 3,
    date: new Date(2025, 6, 4),
    items: [
      { productIdx: 13, qty: 1 },
      { productIdx: 12, qty: 1 },
    ],
    paymentType: "Card",
  },
  {
    userIdx: 0,
    date: new Date(2025, 6, 15),
    items: [
      { productIdx: 3, qty: 1 },
      { productIdx: 8, qty: 1 },
    ],
    paymentType: "EFT",
  },
  {
    userIdx: 1,
    date: new Date(2025, 6, 22),
    items: [
      { productIdx: 0, qty: 1 },
      { productIdx: 16, qty: 1 },
    ],
    paymentType: "Card",
  },
  {
    userIdx: 2,
    date: new Date(2025, 6, 30),
    items: [{ productIdx: 10, qty: 1 }],
    paymentType: "EFT",
  },

  // ── Aug 2025 (5 orders) — User 4 first appears ─────────────────────────
  {
    userIdx: 4,
    date: new Date(2025, 7, 2),
    items: [{ productIdx: 23, qty: 1 }],
    paymentType: "Card",
  },
  {
    userIdx: 0,
    date: new Date(2025, 7, 10),
    items: [{ productIdx: 13, qty: 1 }],
    paymentType: "Cash on Delivery",
  },
  {
    userIdx: 3,
    date: new Date(2025, 7, 15),
    items: [{ productIdx: 0, qty: 1 }],
    paymentType: "Card",
  },
  {
    userIdx: 1,
    date: new Date(2025, 7, 20),
    items: [
      { productIdx: 5, qty: 1 },
      { productIdx: 11, qty: 1 },
      { productIdx: 7, qty: 1 },
    ],
    paymentType: "EFT",
  },
  {
    userIdx: 2,
    date: new Date(2025, 7, 28),
    items: [{ productIdx: 2, qty: 1 }],
    paymentType: "Card",
  },

  // ── Sep 2025 (5 orders) — User 5 first appears ─────────────────────────
  {
    userIdx: 5,
    date: new Date(2025, 8, 3),
    items: [
      { productIdx: 10, qty: 1 },
      { productIdx: 9, qty: 1 },
    ],
    paymentType: "EFT",
  },
  {
    userIdx: 0,
    date: new Date(2025, 8, 8),
    items: [{ productIdx: 1, qty: 1 }],
    paymentType: "Card",
  },
  {
    userIdx: 4,
    date: new Date(2025, 8, 15),
    items: [
      { productIdx: 6, qty: 1 },
      { productIdx: 14, qty: 1 },
    ],
    paymentType: "Cash on Delivery",
  },
  {
    userIdx: 3,
    date: new Date(2025, 8, 22),
    items: [
      { productIdx: 15, qty: 1 },
      { productIdx: 17, qty: 1 },
    ],
    paymentType: "EFT",
  },
  {
    userIdx: 1,
    date: new Date(2025, 8, 28),
    items: [{ productIdx: 3, qty: 1 }],
    paymentType: "Card",
  },

  // ── Oct 2025 (5 orders) — User 6 first appears ─────────────────────────
  {
    userIdx: 6,
    date: new Date(2025, 9, 2),
    items: [{ productIdx: 13, qty: 1 }],
    paymentType: "Card",
  },
  {
    userIdx: 0,
    date: new Date(2025, 9, 8),
    items: [
      { productIdx: 10, qty: 1 },
      { productIdx: 16, qty: 1 },
    ],
    paymentType: "EFT",
  },
  {
    userIdx: 5,
    date: new Date(2025, 9, 14),
    items: [{ productIdx: 0, qty: 1 }],
    paymentType: "Cash on Delivery",
  },
  {
    userIdx: 4,
    date: new Date(2025, 9, 20),
    items: [
      { productIdx: 7, qty: 1 },
      { productIdx: 18, qty: 1 },
    ],
    paymentType: "Card",
  },
  {
    userIdx: 2,
    date: new Date(2025, 9, 26),
    items: [{ productIdx: 1, qty: 1 }],
    paymentType: "EFT",
  },

  // ── Nov 2025 (5 orders) — User 7 first appears ─────────────────────────
  {
    userIdx: 7,
    date: new Date(2025, 10, 1),
    items: [{ productIdx: 10, qty: 1 }],
    paymentType: "Card",
  },
  {
    userIdx: 6,
    date: new Date(2025, 10, 10),
    items: [
      { productIdx: 3, qty: 1 },
      { productIdx: 17, qty: 1 },
    ],
    paymentType: "Card",
  },
  {
    userIdx: 3,
    date: new Date(2025, 10, 16),
    items: [
      { productIdx: 12, qty: 1 },
      { productIdx: 11, qty: 1 },
    ],
    paymentType: "Cash on Delivery",
  },
  {
    userIdx: 1,
    date: new Date(2025, 10, 22),
    items: [{ productIdx: 0, qty: 1 }],
    paymentType: "Card",
  },
  {
    userIdx: 5,
    date: new Date(2025, 10, 28),
    items: [
      { productIdx: 15, qty: 1 },
      { productIdx: 6, qty: 1 },
    ],
    paymentType: "EFT",
  },

  // ── Dec 2025 (6 orders) — User 8 first appears ─────────────────────────
  {
    userIdx: 8,
    date: new Date(2025, 11, 1),
    items: [{ productIdx: 13, qty: 1 }],
    paymentType: "Card",
  },
  {
    userIdx: 0,
    date: new Date(2025, 11, 5),
    items: [
      { productIdx: 2, qty: 1 },
      { productIdx: 19, qty: 1 },
    ],
    paymentType: "EFT",
  },
  {
    userIdx: 7,
    date: new Date(2025, 11, 10),
    items: [{ productIdx: 10, qty: 1 }],
    paymentType: "Cash on Delivery",
  },
  {
    userIdx: 4,
    date: new Date(2025, 11, 15),
    items: [
      { productIdx: 20, qty: 1 },
      { productIdx: 22, qty: 1 },
    ],
    paymentType: "Card",
  },
  {
    userIdx: 6,
    date: new Date(2025, 11, 20),
    items: [
      { productIdx: 5, qty: 1 },
      { productIdx: 24, qty: 1 },
    ],
    paymentType: "EFT",
  },
  {
    userIdx: 3,
    date: new Date(2025, 11, 26),
    items: [{ productIdx: 1, qty: 1 }],
    paymentType: "Card",
  },

  // ── Jan 2026 (7 orders) — User 9 first appears ─────────────────────────
  {
    userIdx: 9,
    date: new Date(2026, 0, 3),
    items: [{ productIdx: 10, qty: 1 }],
    paymentType: "Card",
  },
  {
    userIdx: 0,
    date: new Date(2026, 0, 7),
    items: [
      { productIdx: 0, qty: 1 },
      { productIdx: 14, qty: 1 },
    ],
    paymentType: "EFT",
  },
  {
    userIdx: 8,
    date: new Date(2026, 0, 12),
    items: [{ productIdx: 13, qty: 1 }],
    paymentType: "Cash on Delivery",
  },
  {
    userIdx: 7,
    date: new Date(2026, 0, 17),
    items: [
      { productIdx: 21, qty: 1 },
      { productIdx: 20, qty: 1 },
    ],
    paymentType: "Card",
  },
  {
    userIdx: 5,
    date: new Date(2026, 0, 22),
    items: [{ productIdx: 3, qty: 1 }],
    paymentType: "EFT",
  },
  {
    userIdx: 1,
    date: new Date(2026, 0, 26),
    items: [
      { productIdx: 16, qty: 1 },
      { productIdx: 15, qty: 1 },
    ],
    paymentType: "Card",
  },
  {
    userIdx: 2,
    date: new Date(2026, 0, 30),
    items: [{ productIdx: 11, qty: 1 }],
    paymentType: "Cash on Delivery",
  },

  // ── Feb 2026 (6 orders) — no new customers ─────────────────────────────
  {
    userIdx: 0,
    date: new Date(2026, 1, 3),
    items: [{ productIdx: 0, qty: 1 }],
    paymentType: "Card",
  },
  {
    userIdx: 6,
    date: new Date(2026, 1, 8),
    items: [
      { productIdx: 24, qty: 1 },
      { productIdx: 21, qty: 1 },
    ],
    paymentType: "EFT",
  },
  {
    userIdx: 4,
    date: new Date(2026, 1, 13),
    items: [{ productIdx: 1, qty: 1 }],
    paymentType: "Card",
  },
  {
    userIdx: 3,
    date: new Date(2026, 1, 15),
    items: [{ productIdx: 2, qty: 1 }],
    paymentType: "EFT",
  },
  {
    userIdx: 8,
    date: new Date(2026, 1, 18),
    items: [{ productIdx: 23, qty: 1 }],
    paymentType: "Cash on Delivery",
  },
  {
    userIdx: 7,
    date: new Date(2026, 1, 24),
    items: [{ productIdx: 12, qty: 1 }],
    paymentType: "Card",
  },
];

// ─── Main seed function ──────────────────────────────────────────────────────

async function seed() {
  console.log("╔══════════════════════════════════════╗");
  console.log("║       SEEDING FIREBASE DATABASE      ║");
  console.log("╚══════════════════════════════════════╝\n");

  // ── Step 1: Wipe all existing data ──────────────────────────────────────
  console.log("① Wiping existing Firestore data...");
  const prodCount = await wipeCollection("products");
  const orderCount = await wipeCollection("orders");
  const userCount = await wipeCollection("users");
  console.log(
    `   Deleted: ${prodCount} products, ${orderCount} orders, ${userCount} users\n`,
  );

  // ── Step 2: Compute salesCount per product from order plans ─────────────
  const salesCounts = new Array(products.length).fill(0);
  for (const plan of ORDER_PLANS) {
    for (const item of plan.items) {
      salesCounts[item.productIdx] += item.qty;
    }
  }

  // ── Step 3: Seed products ───────────────────────────────────────────────
  console.log("② Seeding 25 products...");
  const productIds: string[] = [];

  for (let i = 0; i < products.length; i++) {
    const p = products[i];
    const onSale = p.discount.amount > 0 || p.discount.percentage > 0;
    const featured = p.featured ?? false;

    const docRef = await addDoc(collection(db, "products"), {
      ...p,
      featured,
      onSale,
      viewCount: VIEW_COUNTS[i],
      salesCount: salesCounts[i],
      createdAt: Timestamp.now(),
      updatedAt: Timestamp.now(),
    });
    productIds.push(docRef.id);
    console.log(
      `   ✓ ${p.name} → ${salesCounts[i]} sold, ${VIEW_COUNTS[i]} views` +
        (featured ? " [FEATURED]" : "") +
        (onSale ? " [ON SALE]" : ""),
    );
  }
  console.log();

  // ── Step 4: Seed users (Firebase Auth + Firestore) ──────────────────────
  console.log("③ Seeding 11 users (10 customers + 1 admin)...");
  console.log("   (If user exists in Auth, will sign in to reuse UID)\n");
  const userUids: string[] = [];

  for (let i = 0; i < DEMO_USERS.length; i++) {
    const user = DEMO_USERS[i];
    let uid: string;
    let existed = false;

    try {
      const cred = await createUserWithEmailAndPassword(
        auth,
        user.email,
        DEMO_PASSWORD,
      );
      uid = cred.user.uid;
    } catch (err: any) {
      if (err.code === "auth/email-already-in-use") {
        const cred = await signInWithEmailAndPassword(
          auth,
          user.email,
          DEMO_PASSWORD,
        );
        uid = cred.user.uid;
        existed = true;
      } else {
        console.error(`   ✗ Failed: ${user.email}`, err.message);
        throw err;
      }
    }

    // Write user doc to Firestore (overwrites if exists)
    // Give each customer a saved address (admin gets none)
    const userAddress =
      user.role === "customer"
        ? [
            {
              id: `addr-${i + 1}`,
              addressType: "Residential" as const,
              ...ADDRESSES[i % ADDRESSES.length],
            },
          ]
        : [];

    await setDoc(doc(db, "users", uid), {
      email: user.email,
      displayName: user.displayName,
      role: user.role,
      addresses: userAddress,
      wishlist: [],
      priceWatchers: [],
      autoBuyMessages: [],
      friendCode: generateFriendCode(),
      friends: [],
      incomingRequests: [],
      outgoingRequests: [],
      createdAt: Timestamp.fromDate(user.createdAt),
    });

    userUids.push(uid);
    console.log(
      `   ✓ ${user.displayName.padEnd(16)} ${user.email.padEnd(22)} ${user.role.padEnd(10)} uid: ${uid}` +
        (existed ? " (reused)" : " (created)"),
    );

    // Small delay to avoid Auth rate-limiting
    await delay(300);
  }
  console.log();

  // ── Step 5: Seed orders ─────────────────────────────────────────────────
  console.log("④ Seeding 50 orders...");

  for (let i = 0; i < ORDER_PLANS.length; i++) {
    const plan = ORDER_PLANS[i];
    const userId = userUids[plan.userIdx];

    // Build order items from product data
    const items = plan.items.map((item) => ({
      productId: productIds[item.productIdx],
      name: products[item.productIdx].name,
      price: products[item.productIdx].price,
      quantity: item.qty,
      image: products[item.productIdx].images[0],
    }));

    const totalAmount = items.reduce((s, it) => s + it.price * it.quantity, 0);
    const totalCost = plan.items.reduce(
      (s, it) => s + products[it.productIdx].cost * it.qty,
      0,
    );

    const ts = Timestamp.fromDate(plan.date);

    await addDoc(collection(db, "orders"), {
      userId,
      items,
      totalAmount,
      totalCost,
      shippingAddress: ADDRESSES[plan.userIdx % ADDRESSES.length],
      paymentType: plan.paymentType,
      status: "complete" as const,
      isGift: false,
      isAutoBuy: false,
      createdAt: ts,
      updatedAt: ts,
    });

    const dateStr = plan.date.toLocaleDateString("en-ZA", {
      day: "numeric",
      month: "short",
      year: "numeric",
    });
    const itemNames = plan.items
      .map((it) => products[it.productIdx].name)
      .join(", ");
    console.log(
      `   ✓ #${String(i + 1).padStart(2, "0")}  ${DEMO_USERS[plan.userIdx].displayName.padEnd(16)} ${dateStr.padEnd(14)} ${plan.paymentType.padEnd(18)} ${itemNames}`,
    );
  }

  // ── Summary ─────────────────────────────────────────────────────────────
  const totalUnits = salesCounts.reduce((a: number, b: number) => a + b, 0);
  console.log("\n╔══════════════════════════════════════╗");
  console.log("║            SEED COMPLETE!            ║");
  console.log("╚══════════════════════════════════════╝");
  console.log(`   Products:  ${products.length}`);
  console.log(
    `   Users:     ${DEMO_USERS.length} (${DEMO_USERS.filter((u) => u.role === "customer").length} customers + 1 admin)`,
  );
  console.log(
    `   Orders:    ${ORDER_PLANS.length} (${totalUnits} total units sold)`,
  );
  console.log(`   Period:    May 2025 – Feb 2026`);
  console.log(`   Password:  ${DEMO_PASSWORD} (all users)\n`);

  process.exit(0);
}

seed();
